# Generated by Django 4.2.2 on 2023-06-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='static/channels/img/default.jpeg', upload_to='channels/static/channels/img')),
                ('channelName', models.CharField(max_length=255)),
            ],
        ),
    ]
