# Generated by Django 4.2.2 on 2023-06-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='src',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channelName',
            field=models.CharField(max_length=255),
        ),
    ]
