# Generated by Django 4.2.2 on 2023-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_src_alter_channel_channelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='src',
            field=models.CharField(default='https://i.imgur.com/krCbv83.png', max_length=255),
        ),
    ]
