# Generated by Django 4.2.2 on 2023-06-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channel_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, upload_to='channels/static/channels/img'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='src',
            field=models.TextField(default='https://i.imgur.com/krCbv83.png'),
        ),
    ]
