# Generated by Django 4.2.2 on 2023-06-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_remove_channel_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='image',
        ),
        migrations.AddField(
            model_name='channel',
            name='src',
            field=models.TextField(default='https://i.imgur.com/krCbv83.png'),
        ),
    ]
