# Generated by Django 4.2.2 on 2023-06-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_remove_channel_image_channel_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='src',
        ),
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, upload_to='channels/static/channels/img'),
        ),
    ]
