# Generated by Django 4.2.2 on 2023-06-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_remove_channel_src_channel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, default='static/channels/img/9WBG5tw.jpeg', upload_to='channels/static/channels/img'),
        ),
    ]
