# Generated by Django 4.2.2 on 2023-06-25 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creator',
        ),
        migrations.AddField(
            model_name='article',
            name='creators',
            field=models.ManyToManyField(related_name='created_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
